default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: bugs_development

test: &test
  <<: *default
  database: bugs_test

production:
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
